remote_theme: pages-themes/minimal@v0.2.0
logo: Images/IMG_3533.jpg
title: Alyssa Ahn 
description: ğŸ“ San Francisco, California 
"|" ğŸ‘©â€ğŸ’» @ Microsoft 
"|" Hobbies: Biking, Cooking, Hiking, Running, Reading
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
